#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
    
 #HcariCP
  #thymeleaf
spring:
  datasource:
    url: jdbc:mysql:///jtsys?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: lizi7801244
 
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
 
#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations: 
  - classpath:/mapper/*/*.xml
  
  
#log

logging:
  level:
    com.renbenshan: debug
    

    
